server:
  port: 8081

spring:
  application:
    name: userManagement-service

  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/userManagement_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:changeme}

  sql:
    init:
      mode: always
      platform: postgresql

  security:
    bcrypt:
      strength: 12  # Fuerza del hash para contraseñas

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:86400000} # 1 día en milisegundos
