server:
  port: 8081

spring:
  application:
    name: userManagement-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userManagement_db
    username: postgres
    password: "12345"

  sql:
    init:
      mode: always
      platform: postgresql

  security:
    bcrypt:
      strength: 12  # Fuerza del hash para contraseñas

jwt:
  secret: mySecretKey1234567890abcdef1234567890abcdef
  expiration: 86400000 # 1 día en milisegundos
